config/routes.rb
Rails.application.routes.draw do
  root 'party_loot_splitter#calculator'

  post 'party_loot_splitter/result'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/party_loot_splitter_controller.rb
class PartyLootSplitterController < ApplicationController
  def calculator
    @split_options = SplitCalculator::SPLIT_LOGIC.map { |element| [element[:message], element[:key]] }
  end

  def result
    split_calculator = SplitCalculator.new(params[:split_logic], params[:party_hunt_log])

    split_calculator_policy = SplitCalculatorPolicy.new(split_calculator)

    @data = if split_calculator_policy.can_perform_split?
              split_calculator.calculate
            else
              split_calculator_policy.humanize_errors
            end
  rescue StandardError => _e
    @data = { errors: ['Errors while parsing input or calculating the result.'] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/party_loot_splitter_helper.rb
module PartyLootSplitterHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tibia - Party Loot Splitter</title>
    <meta name='viewport' content='width=device-width,initial-scale=1'>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <br />
    <div class='container'>
      <div class='columns'>
        <div class='column'></div>
        <div class='column is-four-fifths'>
          <div class='box'>
            <div class='level-item has-text-centered'>
              <%= image_tag('header.png') %>
            </div>

            <br />

            <%= yield %>
          </div>
        </div>
        <div class='column'></div>
      </div>
    </div>
  </body>
</html>

app/views/party_loot_splitter/calculator.html.erb
<%= form_with url: party_loot_splitter_result_path, method: :post do |form| %>
  <div class='field-label'>
    <%= form.label :party_hunt_log, 'Input Tibia’s Party Hunt Analyser', class: 'label' %>
  </div>

  <br />

  <div class='field-body'>
    <div class='field'>
      <div class='select is-primary'>
        <%= select_tag(:split_logic, options_for_select(@split_options)) %>
      </div>
    </div>
  </div>

  <br />

  <div class='field-body'>
    <div class='field'>
      <div class='control'>
        <%= form.text_area :party_hunt_log, class: 'textarea', rows: 15 %>
      </div>
    </div>
  </div>

  <br />

  <div class='control'>
    <%= form.submit 'Submit', class: 'button is-primary' %>
  </div>
<% end %>

app/views/party_loot_splitter/result.html.erb
<div class='content'>
  <% if @data.has_key? :errors %>
  <h1 class='title'>Error</h1>

  <p>The following error/s occurred:</p>

  <% @data[:errors].each do |error| %>
  <div class='notification is-danger'>
    <button class='delete'></button>
    <%= error %>
  </div>
  <% end %>
  <% else %>
  <h1 class='title'>Loot Type: <%= @data[:loot_type] %> - Duration: <%= @data[:duration] %></h1>

  <p>Copy bold part and say it to a Bank NPC to quickly make the transfer.</p>

  <ul>
    <% @data[:transfers].each do |transfer| %>
    <li><%= transfer[:from] %> should <strong>transfer <%= transfer[:amount] %> to <%= transfer[:to] %></strong>.</li>
    <% end %>
  </ul>
  <% end %>
</div>